export const ROUTES = {
  home: "/",
  products: "/products",
  product: (slug: string) => `/products/${slug}`,
  categories: "/categories",
  category: (slug: string) => `/categories/${slug}`,
  search: "/search",
  cart: "/cart",
  wishlist: "/wishlist",
  checkout: "/checkout",
  orders: "/orders",
  order: (id: string) => `/orders/${id}`,
  profile: "/profile",
  account: "/account",
  addresses: "/account/addresses",
  notifications: "/account/notifications",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  verifyEmail: "/auth/verify-email",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  contact: "/contact",
  about: "/about",
} as const;
