export const ROUTES = {
  home: "/",
  products: "/products",
  product: (slug: string) => `/products/${slug}`,
  categories: "/categories",
  category: (slug: string) => `/categories/${slug}`,
  brands: "/brands",
  brand: (slug: string) => `/brands/${slug}`,
  search: "/search",
  cart: "/cart",
  wishlist: "/wishlist",
  checkout: "/checkout",
  checkoutSuccess: (orderNumber: string) => `/checkout/success/${orderNumber}`,
  orders: "/orders",
  order: (id: string) => `/orders/${id}`,
  profile: "/profile",
  account: "/account",
  addresses: "/account/addresses",
  notifications: "/account/notifications",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  verifyEmail: "/auth/verify-email",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminAnalytics: "/admin/analytics",
  adminInventory: "/admin/inventory",
  adminProducts: "/admin/products",
  adminProductNew: "/admin/products/new",
  adminProductEdit: (id: string) => `/admin/products/${id}/edit`,
  adminCategories: "/admin/categories",
  adminSubCategories: "/admin/subcategories",
  adminBrands: "/admin/brands",
  adminOrders: "/admin/orders",
  adminReviews: "/admin/reviews",
  adminCustomers: "/admin/customers",
  adminSettings: "/admin/settings",
  contact: "/contact",
  about: "/about",
  returnPolicy: "/return-refund-policy",
} as const;
